name: CI Pipeline for Kruize UI

# Triggers the workflow on push or pull request to the mvp_demo branch
on:
  push:
    branches: [mvp_demo]
  pull_request:
    branches: [mvp_demo]

# Define the jobs to run as part of this workflow

jobs:
  #Job 1
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (specify version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm config set legacy-peer-deps true && npm install

      # Step 4: Build the UI
      - name: Build UI
        run: npm run build

  #Job 2
  unit-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (specify version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm config set legacy-peer-deps true && npm install

      # # Step 4: Run Tests
      - name: Run Tests
        run: npm run test

  run-local-monitoring:
    runs-on: ubuntu-latest # or choose any runner based on your needs

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Checkout the kruize-demos repository
        uses: actions/checkout@v3
        with:
          repository: kruize/kruize-demos # Clone the kruize-demos repo
          path: kruize-demos # Optional path to store the repo locally

      - name: Run Local Monitoring Demo Script
        run: |
          chmod +x ./kruize-demos/monitoring/local_monitoring/local_monitoring_demo.sh
          ./kruize-demos/monitoring/local_monitoring/local_monitoring_demo.sh -c minikube -e container
